# Site Configuration

title: Shaw Sun
tagline: "Robotics Engineer"
description: >-
  A cyber storage

url: 'https://sxy-sun.github.io'
baseurl: ""

lang: en
timezone: America/Detroit

avatar: '/assets/figures/favicon.png'

github:
  username: sxy-sun
social:
  name: Shaw Sun
  email: example@domain.com
  links:
    - https://github.com/sxy-sun
    - https://www.linkedin.com/in/sunxiaoyu/

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE
  - Gemfile.lock

jekyll-archives:
  enabled: [categories]
  layouts:
    category: category
  permalinks:
    category: /categories/:name/
